Q1

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [20]:
Q1_array=np.array(np.random.uniform(-1,1,10))
print(Q1_array)

[-0.12321398 -0.23312898  0.99189882 -0.73735257  0.19358786  0.00539578
 -0.91184391  0.52088856  0.70916045  0.81869992]


In [32]:
Q1_array[-6::-1]

array([ 0.19358786, -0.73735257,  0.99189882, -0.23312898, -0.12321398])

In [57]:
Q2_array=np.array([np.random.uniform(-1,1,4),
                  np.random.uniform(-1,1,4),
                  np.random.uniform(-1,1,4)])
Q2_array

array([[-0.1164875 , -0.46506487,  0.31978294, -0.98100107],
       [ 0.72834684, -0.05826756, -0.0237464 , -0.55605405],
       [ 0.62734001, -0.98442048, -0.67427915,  0.93860917]])

In [61]:
Q2_array[np.ix_([0,2],[1,3])]

array([[-0.46506487, -0.98100107],
       [-0.98442048,  0.93860917]])

In [83]:
Q3_array=np.random.uniform(-1,1,size=(4,5,6))
Q3_array

array([[[-0.63247334, -0.00116401,  0.4897203 , -0.27846128,
         -0.18049213, -0.38979314],
        [-0.48505543, -0.40176798,  0.17327356,  0.25063145,
         -0.48087959,  0.76148897],
        [ 0.0544112 , -0.94275306, -0.49568544, -0.9487244 ,
         -0.1325508 ,  0.98670681],
        [-0.46701792,  0.56511191, -0.88256432, -0.11012126,
          0.83242796,  0.50414105],
        [ 0.30858289,  0.09068018, -0.31091897, -0.05009742,
         -0.02112428,  0.97413589]],

       [[-0.9930265 , -0.24147512, -0.80207783,  0.53460045,
         -0.6980495 ,  0.83804998],
        [ 0.52759393, -0.47644902,  0.81595537,  0.66361397,
         -0.82695676, -0.33536862],
        [ 0.98636073,  0.77262602, -0.32664988,  0.99343341,
         -0.43241746,  0.43166969],
        [ 0.27153923,  0.33337082, -0.03129085, -0.79267841,
          0.42319597,  0.41824748],
        [ 0.46371097, -0.79828867, -0.23090143, -0.25844173,
         -0.29722072,  0.53331394]],

       [[ 0.94988991,  0.3

In [85]:
Q3_array[0,1,:]

array([-0.48505543, -0.40176798,  0.17327356,  0.25063145, -0.48087959,
        0.76148897])

In [97]:
Q3_array[...,:2]

array([[[-0.63247334, -0.00116401],
        [-0.48505543, -0.40176798],
        [ 0.0544112 , -0.94275306],
        [-0.46701792,  0.56511191],
        [ 0.30858289,  0.09068018]],

       [[-0.9930265 , -0.24147512],
        [ 0.52759393, -0.47644902],
        [ 0.98636073,  0.77262602],
        [ 0.27153923,  0.33337082],
        [ 0.46371097, -0.79828867]],

       [[ 0.94988991,  0.34280487],
        [ 0.04963659,  0.67676573],
        [-0.18451766,  0.31071601],
        [ 0.1389581 , -0.76034573],
        [-0.68625557,  0.73032951]],

       [[ 0.71628797, -0.97901233],
        [ 0.91149654,  0.01042388],
        [ 0.08841531,  0.1641779 ],
        [-0.49191417,  0.81123009],
        [-0.92872866,  0.96430003]]])