In [11]:
value=input("输入一个数值")

if value.isdigit():
    number=int(value)
    if 0<= number <=100:
        if number<60:
            print("不及格")
        else:
            print("及格")
    else:
        print("数值不在0~100之中")
else:
    print("输入不是数值")


输入一个数值 300


数值不在0~100之中


In [15]:
num=input('输入一个整数')
num=int(num)
if num>0:
    print("num is positive")
elif num<0:
    print("num is negative")
else:
    print("num is zero")

输入一个整数 1


num is positive


In [19]:
for i in range(1,6):
    if i==3:
        break
    print(i)

1
2


In [21]:
for i in range(1,6):
    if i==3:
        continue
    print(i)

1
2
4
5


In [23]:
for i in range(1,6):
    pass
    print(i)

1
2
3
4
5


In [25]:
a=[1,2,3,4,5]
b=[6,7,8,9,0]

dot_product=0

for i in range(len(a)):
    dot_product+=a[i]*b[i]

print("向量内积:",dot_product)

向量内积: 80


In [31]:
for i in range(4+1):
    print(i)

for i in range(10,20+1):
    print(i)

for i in range(1,10+1,2):
    print(i)

for i in range(10,1-1,-1):
    print(i)

list(range(10,1-1,-1))

0
1
2
3
4
10
11
12
13
14
15
16
17
18
19
20
1
3
5
7
9
10
9
8
7
6
5
4
3
2
1


[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [33]:
fruits=['apple','banana','cherry']

for index,fruit in enumerate(fruits):
    print(index,fruit)

0 apple
1 banana
2 cherry


In [37]:
fruits=['apple','banana','cherry']

for index,fruit in enumerate(fruits,1):
    print(index,fruit)

1 apple
2 banana
3 cherry


In [49]:
import itertools

names=['Alice','Bob','Charlie','qq','a']
scores=[80,90,75]

for name,score in zip(names,scores):
    print(name,score)

for i in itertools.zip_longest(names,scores):
    print(i)

Alice 80
Bob 90
Charlie 75
('Alice', 80)
('Bob', 90)
('Charlie', 75)
('qq', None)
('a', None)


In [51]:
a=[1,2,3,4,5]
b=[6,7,8,9,0]

dot_product=0

for a_i,b_i in zip(a,b):
    dot_product+=(a_i*b_i)

print(dot_product)

80


In [53]:
def custom_meshgrid(x,y):

    num_x=len(x);num_y=len(y)
    X=[];Y=[]

    for i in range(num_y):
        X_row=[];Y_row=[]
        for j in range(num_x):
            X_row.append(x[j])
            Y_row.append(y[i])
        X.append(X_row);Y.append(Y_row)
    return X,Y

#示例
x=[0,1,2,3,4,5]
y=[0,1,2,3]

X,Y=custom_meshgrid(x,y)
print("X");print(X)
print("Y");print(Y)

X
[[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]]
Y
[[0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1], [2, 2, 2, 2, 2, 2], [3, 3, 3, 3, 3, 3]]


In [57]:
A=[[1,2,10,20],
   [3,4,30,40],
   [5,6,50,60]]

B=[[4,2],
   [3,1],
   [40,20],
   [30,10]]
#定义全0矩阵C用于存储结果
C=[[0,0],
   [0,0],
   [0,0]]

#矩阵乘法
#遍历A的行

for i in range(len(A)):#给出A的行数
    for j in range(len(B[0])):#给出了B的列数
        #消除k所在维度 A行与B列相乘取内积(压缩)
        for k in range(len(B)):#取出b的行数,因为a列与b行相同所以需要乘以4次
            #先取出数列中的对应数列 然后取出数列中的值进行多次循环
            C[i][j]+=A[i][k]*B[k][j]
            #完成一次求和

for row in C:
    print(row)

[1010, 404]
[2424, 1010]
[3838, 1616]


In [61]:
A=[[1,2,10,20],
   [3,4,30,40],
   [5,6,50,60]]

B=[[4,2],
   [3,1],
   [40,20],
   [30,10]]
#定义全0矩阵C用于存储结果
C=[[0,0],
   [0,0],
   [0,0]]

#矩阵乘法
#遍历A的行

for j in range(len(B[0])):#给出B的列数
    for i in range(len(A)):#给出了A的行数
        #消除k所在维度 A行与B列相乘取内积(压缩)
        for k in range(len(B)):
            #先取出数列中的对应数列 
            C[i][j]+=A[i][k]*B[k][j]
            #完成一次求和

for row in C:
    print(row)

[1010, 404]
[2424, 1010]
[3838, 1616]


In [69]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,0])

#计算向量内积
dot_product=np.dot(a,b)

c=a@b
print(dot_product)
print(c)

80
80


In [65]:
import numpy as np

#定义矩阵A和B
A=np.array([[1,2,10,20],
            [3,4,30,40]])
B=np.array([[1,3],
            [2,4],
            [10,30],
            [20,40]])

C=A@B;print(C)
D=B@A;print(D)

[[ 505 1111]
 [1111 2525]]
[[  10   14  100  140]
 [  14   20  140  200]
 [ 100  140 1000 1400]
 [ 140  200 1400 2000]]


In [1]:
from numpy.random import randint
num=200

#num*num大小方阵0~9的随机数 
A=randint(0,10,size=(num,num))
B=randint(0,10,size=(num,num))

#用Numpy计算矩阵乘法
import time
start_time = time.time()#开始计时
C_1=A@B
stop_time=time.time()#结束计时
time_used=stop_time-start_time
print("--- %s sesonds ---"%time_used)

#num*num 大小的全0方阵
import numpy as np
C_2=np.zeros((num,num))

#手动编程计算
start_time=time.time()

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C_2[i][j]+=A[i][k]*B[k][j]

stop_time=time.time()
time_used=stop_time - start_time
print("--- %s seconds ---"%time_used)

print(C_1==C_2)

--- 0.011200189590454102 sesonds ---
--- 3.787402868270874 seconds ---
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]


In [3]:
even_number=[num for num in range(1,11) if num %2==0]

print(even_number)

[2, 4, 6, 8, 10]


In [7]:
matrix=[[i*j for j in range(1,4)]
        for i in range(1,4)]
print(matrix)

[[1, 2, 3], [2, 4, 6], [3, 6, 9]]


In [17]:
matrix=[[0 for j in range(1,4)] for i in range(1,4)]
print(matrix)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [45]:
#模仿numpy.linspace()函数
def linspace(start,stop,num=50,endpoint=True):
    if num<2:
        #报错
        raise ValueError("Number of samples must be at least 2")
    #是否包含右侧端点
    if start==stop:
        raise ValueError("start can't equal stop")
    if endpoint:
        step=(stop-start)/(num-1)
        return[start+i*step for i in range(num)]
    else:
        step=(stop-start)/num
        return[start+i*step for i in range(num)]

start=0
stop=10
num=10
endpoint=1
values=linspace(start,stop,num,endpoint)
        
print(values)     

[0.0, 1.1111111111111112, 2.2222222222222223, 3.3333333333333335, 4.444444444444445, 5.555555555555555, 6.666666666666667, 7.777777777777779, 8.88888888888889, 10.0]


In [49]:
def transpose(matrix):
    transposed=[]
    rows=len(matrix)
    cols=len(matrix[0])

    for j in range(cols):
        transposed_row=[matrix[i][j]
                        for i in range(rows)]
        transposed.append(transposed_row)
    return transposed

A=[[1,2,3],
   [4,5,6]]
B=transpose(A)
print(B)

[[1, 4], [2, 5], [3, 6]]


In [57]:
def transpose_2(matrix):
    transposed=[]
    rows=len(matrix)
    cols=len(matrix)

    transposed=[[matrix[j][i]
                for j in range(rows)]
                for i in range(cols)]
    return transposed

A=[[1,2,3],
   [4,5,6]]

B=transpose_2(A)
print(B)

[[1, 4], [2, 5]]


In [65]:
def hadamard_prod(M1,M2):
    if (len(M1) != len(M2) or 
        len(M1[0]) != len(M2[0])):
        raise ValueError("Matrices must have the same shape")

    result=[[M1[i][j]*M2[i][j]
             for j in range(len(M1[0]))]
            for i in range(len(M1))]
    return result

A=[[1,2],
   [3,4]]
B=[[2,3],
   [4,5]]

C=hadamard_prod(A,B)
print(C)

[[2, 6], [12, 20]]


In [67]:
column1=[1,2,3,4]
column2=['a','b','c']

cartesian_product=[(x,y) for x in column1 for y in column2]
print(cartesian_product)

[(1, 'a'), (1, 'b'), (1, 'c'), (2, 'a'), (2, 'b'), (2, 'c'), (3, 'a'), (3, 'b'), (3, 'c'), (4, 'a'), (4, 'b'), (4, 'c')]


In [70]:
column1=[1,2,3,4]
column2=['a','b','c']
cartesian_product=[[(x,y) for x in column1] for y in column2]

for prod_idx in cartesian_product:
    print(prod_idx)

[(1, 'a'), (2, 'a'), (3, 'a'), (4, 'a')]
[(1, 'b'), (2, 'b'), (3, 'b'), (4, 'b')]
[(1, 'c'), (2, 'c'), (3, 'c'), (4, 'c')]


In [74]:
from itertools import product
column1=[1,2,3,4]
column2=['a','b','c','d']

cartesian_product=list(product(column1,column2))
print(cartesian_product)

[(1, 'a'), (1, 'b'), (1, 'c'), (1, 'd'), (2, 'a'), (2, 'b'), (2, 'c'), (2, 'd'), (3, 'a'), (3, 'b'), (3, 'c'), (3, 'd'), (4, 'a'), (4, 'b'), (4, 'c'), (4, 'd')]


In [82]:
import itertools
string=['ab','bc','cd']
perms_all= itertools.permutations(string)

for perm_idx in perms_all:
    print(''.join(perm_idx))

abbccd
abcdbc
bcabcd
bccdab
cdabbc
cdbcab


In [84]:
import itertools
string='abc'

perms_2=itertools.permutations(string,2)

for perms_idx in perms_2:
    print(''.join(perms_idx))

ab
ac
ba
bc
ca
cb


In [86]:
import itertools
string='abc'
combs_2=itertools.combinations(string,2)

for combo_idx in combs_2:
    print(''.join(combo_idx))

ab
ac
bc


In [96]:
import itertools

string='abc'
elements=list(string)
repeat=2

permutations=itertools.product(elements,repeat=repeat)

for permutation_idx in permutations:
    print(''.join(permutation_idx))

aa
ab
ac
ba
bb
bc
ca
cb
cc


In [100]:
import itertools
string='abc'
elements=list(string)
length=2
combos=itertools.combinations_with_replacement(elements,length)

for combination_idx in combos:
    print(''.join(combination_idx))

aa
ab
ac
bb
bc
cc
