In [4]:
import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4],dtype=float) #转换数据类型变成浮点型
arr3=np.array([(1,2,3),(4,5,6)])#元组将会转变成数列,嵌套数列的形式
arr4=np.array([1,2,3,4],ndmin=2)#ndmin表示最小维度,强制转变成二维数组,二维数组中的第一个元素为输入的数列

print(arr1)
print(arr2)
print(arr3)
print(arr4)

[1 2 3 4]
[1. 2. 3. 4.]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4]]


In [6]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
from matplotlib import cm

def visualize_2D(array,title,vmax,vmin):

    fig_width=math.ceil(array.shape[1]*0.5)
    fig_length=math.ceil(array.shape[0]*0.5)

    fig,ax=plt.subplots(figsize=(fig_width,fig_length))

    sns.heatmap(array,
                vmax=vmax,
                vmin=vmin,
                annot=True,
                fmt=".0f",
                square=True,
                cmap='RdYlBu_r',
                linewidths=.5,
                cbar=False,
                yticklabels=False,
                xticklabels=False,
                ax=ax)